# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Local repository
      uses: actions/checkout@v4
      with:
        path: Local
    - name: Checkout Charon repository
      uses: actions/checkout@v4
      with:
        repository: montague247/Charon
        token: ${{ secrets.GIT_CHARON_PAT }}
        path: Charon   
    - name: Link Charon
      run: ln -s $(pwd)/Charon $(pwd)/Local/Charon
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore Local/src
    - name: Check file usage
      run: fuser Local/Charon/src/Charon.Core/bin/Debug/net9.0/Charon.Core.deps.json
    - name: Build
      run: dotnet build Local/src --no-restore
    - name: Test
      run: dotnet test Local/src --no-build --verbosity normal
