# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Charon repository
      uses: actions/checkout@v4
      with:
        repository: montague247/Charon
        token: ${{ secrets.GIT_CHARON_PAT }}
        path: Charon
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: NetSentinel
    - name: Link Charon
      run: ln -s Charon NetSentinel/Charon
    - name: List contents of NetSentinel/Charon
      run: ls -la NetSentinel/Charon
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore
    - name: Test
      run: dotnet test src --no-build --verbosity normal
